// packages/ticketing-adapter/src/types.ts — Spec 13 §4, copied verbatim
// (§4.1–§4.5). Non-schema types; this unit's own domain model, deliberately
// separate from @sentinel-act/graph-schema per Spec 13 §1/§3 (this unit
// never writes to the graph — see also GraphQueryPort below, read-only).

// ---------------------------------------------------------------------------
// §4.1 The swappable adapter port
// ---------------------------------------------------------------------------

export type TicketPriority = "P1_urgent" | "P2_high" | "P3_normal";

export interface TicketAssignee {
  /** Resolved queue/user identifier in the external system — a Jira
   *  account id, a ServiceNow assignment-group sys_id, or (for the
   *  generic webhook default) an opaque string the receiving system
   *  interprets itself. */
  externalAssigneeRef: string;
  /** Human-readable label, logging/debugging only — never used for
   *  lookup or comparison. */
  displayLabel: string;
  /** true when RoleAssigneeMapPort had no entry for owner_role and the
   *  configured fallback queue was used instead — see FR-8. */
  isFallback: boolean;
}

export interface CreateTicketRequest {
  /** Idempotency/dedupe key for the *external* system, where supported
   *  (e.g. Jira's "external ID" custom field). Always exactly
   *  ProcessTask.task_id — see §6 Idempotency. Concrete adapters that
   *  cannot enforce dedupe server-side (the generic webhook) rely on this
   *  unit's own outbox + TicketMapping dedupe instead (§6); this field is
   *  still passed through so a smarter receiver can use it too. */
  dedupeKey: string;
  title: string;
  description: string; // markdown; composition rules in FR-7
  assignee: TicketAssignee;
  dueDate: string; // ISO datetime
  priority: TicketPriority;
  labels: string[];
  sourceRefs: {
    obligation_id: string;
    task_id: string;
    circular_id: string | null;
    clause_para_ref: string | null;
  };
}

export interface CreateTicketResult {
  externalTicketId: string;
  externalTicketUrl: string | null;
  raw: unknown; // adapter-specific raw response, stored for debugging only
}

export interface UpdateTicketFields {
  title?: string;
  description?: string;
  assignee?: TicketAssignee;
  dueDate?: string;
  priority?: TicketPriority;
  /** Appended as a ticket comment rather than a field overwrite — the
   *  only update shape this spec's v1 scope actually anticipates a future
   *  caller using (e.g. "this obligation was superseded", §13 item 6). */
  comment?: string;
}

export interface UpdateTicketRequest {
  externalTicketId: string;
  fields: UpdateTicketFields;
}

export interface UpdateTicketResult {
  updated: boolean;
  raw: unknown;
}

/** The swappable port. Jira, ServiceNow, and the generic webhook
 *  reference implementation are all just implementations of this
 *  interface — nothing in the trigger/mapping/idempotency/outbox layer
 *  below (§4.2–§4.4) knows or cares which concrete adapter is wired in.
 *  Exactly one adapter is active per deployment (no fan-out to multiple
 *  ticketing systems in this spec's scope). */
export interface TicketingAdapter {
  readonly adapterName: string; // e.g. "generic-webhook", "jira", "servicenow"
  createTicket(request: CreateTicketRequest): Promise<CreateTicketResult>;
  updateTicket(request: UpdateTicketRequest): Promise<UpdateTicketResult>;
}

// ---------------------------------------------------------------------------
// §4.2 The role -> assignee/queue lookup (open dependency)
// ---------------------------------------------------------------------------

/** Resolves ProcessTask.owner_role (e.g. "Compliance Officer",
 *  "Stockbroker Operations Team") to a real assignee or queue in the
 *  external ticketing system. NO CONCRETE DATA SOURCE FOR THIS EXISTS
 *  YET anywhere in the repo — there is no roster/directory service, no
 *  role-to-user table in the graph schema (IntermediaryCategory is a
 *  regulatory taxonomy, not a staffing directory), and no HR/identity
 *  integration. This is an explicit, flagged open dependency (§13 item 1),
 *  not something this spec invents a fake answer for. */
export interface RoleAssigneeMapPort {
  resolve(owner_role: string): Promise<TicketAssignee | null>; // null = no mapping found
}

// ---------------------------------------------------------------------------
// §4.3 Trigger event (forward-declared additive hook into Spec 08)
// ---------------------------------------------------------------------------

/** Emitted by Spec 08's finalizeCommitStep (FR-27 Tier A path, FR-28
 *  Tier B/C-approved path) immediately after GraphWriter.commitProposal
 *  succeeds — never for a reject or disagreement/escalate outcome
 *  (FR-30/FR-31 there). */
export interface ObligationCommittedEvent {
  event_id: string; // uuid v4, generated by the Orchestrator at emit time
  obligation_id: string;
  task_id: string;
  /** Exactly one of these two — the only ObligationStatus values this
   *  event ever fires for (see §1). */
  final_status: "tier_a_committed" | "committed";
  tier: "A" | "B" | "C" | "ESCALATE";
  committed_at: string; // ISO datetime, matches the commit's recorded_at
}

// ---------------------------------------------------------------------------
// §4.4 Outbox and ticket-mapping (idempotency + async retry state)
// ---------------------------------------------------------------------------

export type OutboxStatus = "pending" | "processing" | "succeeded" | "failed_retryable" | "failed_permanent";

export interface TicketingOutboxEntry {
  id: string; // uuid v4, PK
  event_id: string; // UNIQUE — dedupes a redelivered ObligationCommittedEvent, FR-3
  obligation_id: string;
  task_id: string;
  /** DEVIATION FROM SPEC TEXT (documented, not silent): §4.4's literal
   *  TicketingOutboxEntry shape omits `tier`, yet `buildCreateTicketRequest`
   *  (§5.1) requires the full `ObligationCommittedEvent` — specifically
   *  `event.tier`, consumed by FR-12's label composition. The outbox
   *  worker (processOutboxOnce) only has the persisted outbox row when it
   *  runs, often long after the original in-memory event is gone — an
   *  inherent property of the outbox pattern (the row must carry every
   *  field needed to complete the operation later). `tier` cannot be
   *  reliably re-derived from `Obligation.status` alone at that point,
   *  because both Tier B and Tier C collapse to the same `"committed"`
   *  status once approved. Persisting `event.tier` on the row at insert
   *  time (FR-3) is the minimal fix. */
  tier: "A" | "B" | "C" | "ESCALATE";
  status: OutboxStatus;
  attempts: number;
  next_attempt_at: string; // ISO datetime
  last_error: string | null;
  created_at: string;
  updated_at: string;
}

/** One row per ticket ever created. task_id is the PK: v1 creates at
 *  most one ticket per ProcessTask, ever — this table IS the durable
 *  idempotency store the createTicket dedupe check (FR-4) reads before
 *  calling the adapter. */
export interface TicketMapping {
  task_id: string; // PK
  adapter_name: string;
  external_ticket_id: string;
  external_ticket_url: string | null;
  created_at: string;
}

// ---------------------------------------------------------------------------
// §4.5 Ticketing context (ports this unit is constructed with)
// ---------------------------------------------------------------------------

export interface GraphQueryPort {
  runCypher<T = Record<string, unknown>>(query: string, params: Record<string, unknown>): Promise<T[]>;
}

export interface AppendLedgerEntryPort {
  append(input: {
    event_type: "TICKET_CREATED" | "TICKET_CREATE_FAILED" | "TICKET_UPDATED" | "TICKET_UPDATE_FAILED";
    actor: { type: "system"; id: "grc-ticketing" };
    entity_ref: { entity_type: "ProcessTask"; entity_id: string };
    payload: Record<string, unknown>;
  }): Promise<{ sequence_number: number }>;
}

export interface TicketingOutboxPort {
  insertIfNotExists(
    entry: Omit<TicketingOutboxEntry, "status" | "attempts" | "next_attempt_at" | "last_error" | "created_at" | "updated_at">
  ): Promise<{ inserted: boolean }>;
  claimBatch(limit: number, now: string): Promise<TicketingOutboxEntry[]>; // FR-14's compare-and-set claim
  markSucceeded(id: string): Promise<void>;
  markRetryable(id: string, nextAttemptAt: string, error: string): Promise<void>;
  markPermanentFailure(id: string, error: string): Promise<void>;
  resetToPending(id: string): Promise<void>; // ops utility, FR-18
  findMapping(task_id: string): Promise<TicketMapping | null>;
  insertMapping(mapping: TicketMapping): Promise<{ inserted: boolean }>; // false if task_id already mapped (race, see §8)
  /** Not part of the spec's literal §4.5 listing, but required by FR-19's
   *  reconciliation query ("no in-flight outbox row ... for its task_id")
   *  to be checkable without a second bespoke SQL surface. Returns true if
   *  any outbox row for `task_id` is currently pending/processing/
   *  failed_retryable. */
  hasInFlightEntryForTask(task_id: string): Promise<boolean>;
}

export interface TicketingContext {
  graph: GraphQueryPort; // read-only, same shape as Spec 05/07's GraphQueryPort
  adapter: TicketingAdapter;
  roleAssigneeMap: RoleAssigneeMapPort;
  outbox: TicketingOutboxPort; // Postgres-backed, §6.5
  ledger: AppendLedgerEntryPort; // narrow slice of Spec 07's AuditLedgerPort — append only
  referenceDate: string; // ISO datetime, "now" for all deadline/backoff math — never Date.now() inside pure helpers
  config: {
    defaultAssigneeRef: string; // TICKETING_DEFAULT_QUEUE_REF
    maxAttempts: number; // default 8
    baseBackoffMs: number; // default 60_000 (1 minute)
    maxBackoffMs: number; // default 21_600_000 (6 hours)
    outboxBatchSize: number; // default 20
  };
}

// ---------------------------------------------------------------------------
// §4.6 Read-only Cypher query shapes (documented for callers building their
// own GraphQueryPort-backed lookups; not executable code by themselves).
// ---------------------------------------------------------------------------

/** buildCreateTicketRequest's data source — read-only, mirrors Spec 09's
 *  item-detail query shape.
 *
 *  DEVIATION FROM SPEC TEXT (documented, not silent): §4.6's literal query
 *  omits `circ.circular_id`, yet `CreateTicketRequest.sourceRefs.
 *  circular_id` (§4.1) requires a value. Adding `circ.circular_id AS
 *  circularId` to the RETURN clause (and a matching `circularId` field on
 *  the `lineage` parameter of `buildCreateTicketRequest`) is the minimal
 *  fix — everything else about the query is verbatim from §4.6. */
export const BUILD_TICKET_LINEAGE_CYPHER = `
MATCH (o:Obligation {obligation_id: $obligationId})-[:MAPPED_TO]->(t:ProcessTask {task_id: $taskId})
OPTIONAL MATCH (o)-[:DERIVED_FROM]->(c:Clause)-[:PART_OF]->(circ:Circular)
RETURN o, t, c.para_ref AS clauseParaRef, circ.title AS circularTitle, circ.date_effective AS circularDateEffective, circ.circular_id AS circularId
`;

/** buildCreateTicketRequest's lineage parameter shape — §4.6's 3 named
 *  fields plus `circularId` (see the deviation note on
 *  BUILD_TICKET_LINEAGE_CYPHER above). */
export interface TicketLineage {
  clauseParaRef: string | null;
  circularTitle: string | null;
  circularDateEffective: string | null;
  circularId: string | null;
}
