// Spec 11 §4 (second code block) — POST-REVIEW CORRECTION applied.
//
// This type was originally also named `HumanReviewSubmittedEvent`, an
// accidental name collision with Spec 07 §4's canonical
// `HumanReviewSubmittedEvent` (apps/orchestrator/src/mastra/agents/
// monitoring-and-audit.agent.ts) — a real, incompatible,
// two-specs-define-the-same-type-name bug (Spec 07's version is
// event_id/obligation_id/reviewer_id/tier/decision/rationale/decided_at/
// source/source_ref; this one nests a whole HumanReview object plus
// latency/workflow-state telemetry fields Spec 07's type does not have).
// Renamed to `ReviewSubmissionTelemetryEvent` to make clear this is a
// *distinct*, ops/observability-purpose event, not the graph-write
// payload.
//
// FIX 1 (this unit's implementation): this file deliberately does NOT
// import Spec 07's `HumanReviewSubmittedEvent`. The two types must never
// be confused, and this package is imported by BOTH apps/web-console and
// apps/orchestrator — importing an apps/orchestrator-internal module from
// here would also be a layering violation (apps/orchestrator has no
// main/types/exports field; nothing under its src/** is importable from
// outside that app, see apps/web-console/lib/console/types.ts's own
// "Cross-app importability note"). The actual write payload this unit
// sends to Spec 07's `recordHumanReview` is Spec 07's own
// `HumanReviewSubmittedEvent`, imported unchanged directly in
// apps/orchestrator/src/slack/handlers/view-submissions.ts (see FR-24)
// — NEVER re-declared or re-exported from this package. This type is
// emitted separately, alongside that call, purely for the audit-log/
// telemetry stream both Spec 09's BFF and this unit's Slack gateway write
// to after a successful Orchestrator resume call.
//
// NON-LEAKAGE INVARIANT (§7 NFR-Security-1's sibling in this spec, FR-25):
// `submittedVia` below (and Spec 07's own `HumanReviewSubmittedEvent.source`,
// a *different* field on a *different* type) MUST NEVER be projected into
// any auditor-facing read (Spec 07's ledger export, Spec 10's Observer-mode
// audit search, or a `compliance_head` session response of any kind).

export type ReviewWorkflowState = "suspended" | "resumed_committed" | "resumed_rejected" | "resumed_escalated";

export interface ReviewSubmissionTelemetryEvent {
  /** uuid v4, generated by the caller (BFF or Slack gateway); distinct
   *  from HumanReviewSubmittedEvent.event_id — this is the telemetry
   *  record's own id, not the review's idempotency key. */
  eventId: string;
  obligationId: string;
  reviewerId: string;
  tier: "B" | "C";
  decision: "approve" | "reject";
  workflowState: ReviewWorkflowState;
  /** Time from Orchestrator resume-call-start to response, milliseconds. */
  latencyMs: number;
  /** ISO datetime. */
  emittedAt: string;

  /** Operational/debugging field ONLY. MUST NOT be projected into any
   *  auditor-facing HumanReview read (Spec 07's ledger export, Spec 10's
   *  Observer-mode search) — see this file's top-of-file doc comment and
   *  Spec 11 §7 NFR-Security-1/FR-25. Its only legitimate use is ops
   *  dashboards / on-call debugging of which channel had elevated error
   *  rates. This is the telemetry-stream equivalent of Spec 07
   *  HumanReviewSubmittedEvent.source — the two are populated in
   *  lockstep from the same underlying fact but are different fields on
   *  different types serving different audiences. */
  submittedVia: "console" | "slack";
}
