// Hand-rolled ZIP container writer — an .xlsx file IS a ZIP archive of XML
// parts (OOXML), and this package cannot depend on any ZIP/XLSX library
// (see README.md's "why zero dependencies" section), so this module builds
// the raw byte structure from scratch using only node:zlib's
// `deflateRawSync` (for compression) and this package's own from-scratch
// crc32.ts (for integrity fields the ZIP format itself requires).
//
// Structure produced, per the ZIP spec (PKWARE APPNOTE.TXT §4.3):
//   [local file header + file name + compressed data]   x N, back to back
//   [central directory file header + file name]          x N, back to back
//   [end of central directory record]                     x 1
//
// Compression: method 8 (deflate), via `zlib.deflateRawSync` — chosen over
// method 0 (stored) because it is barely more code once CRC-32 is already
// hand-written (the only other moving part is a compression-method byte
// and calling deflateRawSync instead of copying bytes verbatim), and it
// demonstrates a genuinely compressed, still-valid archive rather than
// leaning on the simplest possible passing case. CRC-32 is always computed
// over the UNCOMPRESSED bytes (per spec), independent of which compression
// method is used.
import { deflateRawSync } from "node:zlib";
import { crc32 } from "./crc32.js";

const LOCAL_FILE_HEADER_SIGNATURE = 0x04034b50;
const CENTRAL_DIRECTORY_SIGNATURE = 0x02014b50;
const END_OF_CENTRAL_DIRECTORY_SIGNATURE = 0x06054b50;
const ZIP_VERSION = 20; // 2.0 — minimum version needed to extract a deflated entry
const COMPRESSION_METHOD_DEFLATE = 8;

export interface ZipEntryInput {
  /** Archive-relative path, e.g. "xl/worksheets/sheet1.xml". Always
   *  forward-slash separated per the ZIP spec, regardless of host OS. */
  name: string;
  /** Uncompressed file content. */
  data: Buffer;
}

/** Encodes a JS Date as the packed 16-bit MS-DOS date/time pair the ZIP
 *  local/central headers require (2-second time resolution, year offset
 *  from 1980 — this is a genuine ZIP-format quirk, not a shortcut taken
 *  here). Only used for the archive's own bookkeeping metadata timestamp,
 *  not for anything Spec 10 FR-18 requires (that lives in sheet2's cell
 *  data, generated by xlsx-generator.ts from the caller-supplied
 *  `generatedAt`). */
function toDosDateTime(date: Date): { dosTime: number; dosDate: number } {
  const dosTime = (date.getHours() << 11) | (date.getMinutes() << 5) | (Math.floor(date.getSeconds() / 2) & 0x1f);
  const dosDate = ((Math.max(0, date.getFullYear() - 1980) & 0x7f) << 9) | ((date.getMonth() + 1) << 5) | date.getDate();
  return { dosTime: dosTime & 0xffff, dosDate: dosDate & 0xffff };
}

/** Builds a complete, valid ZIP archive (as a single Buffer) from a list of
 *  named parts. Every part is compressed independently with
 *  `deflateRawSync`; the archive is otherwise a single-disk ZIP with no
 *  encryption, no comment, and no ZIP64 extension (none of the OOXML parts
 *  this package writes ever approach the 4GB/65535-entry ZIP64 threshold,
 *  so omitting it is a correct simplification, not a gap). */
export function buildZip(entries: ZipEntryInput[]): Buffer {
  const { dosTime, dosDate } = toDosDateTime(new Date());

  const localParts: Buffer[] = [];
  const centralParts: Buffer[] = [];
  let runningOffset = 0;

  for (const entry of entries) {
    const nameBuffer = Buffer.from(entry.name, "utf8");
    const uncompressedCrc32 = crc32(entry.data);
    const compressed = deflateRawSync(entry.data);

    const localHeader = Buffer.alloc(30);
    localHeader.writeUInt32LE(LOCAL_FILE_HEADER_SIGNATURE, 0);
    localHeader.writeUInt16LE(ZIP_VERSION, 4); // version needed to extract
    localHeader.writeUInt16LE(0, 6); // general purpose bit flag
    localHeader.writeUInt16LE(COMPRESSION_METHOD_DEFLATE, 8);
    localHeader.writeUInt16LE(dosTime, 10);
    localHeader.writeUInt16LE(dosDate, 12);
    localHeader.writeUInt32LE(uncompressedCrc32, 14);
    localHeader.writeUInt32LE(compressed.length, 18); // compressed size
    localHeader.writeUInt32LE(entry.data.length, 22); // uncompressed size
    localHeader.writeUInt16LE(nameBuffer.length, 26);
    localHeader.writeUInt16LE(0, 28); // extra field length

    localParts.push(localHeader, nameBuffer, compressed);

    const centralHeader = Buffer.alloc(46);
    centralHeader.writeUInt32LE(CENTRAL_DIRECTORY_SIGNATURE, 0);
    centralHeader.writeUInt16LE(ZIP_VERSION, 4); // version made by
    centralHeader.writeUInt16LE(ZIP_VERSION, 6); // version needed to extract
    centralHeader.writeUInt16LE(0, 8); // general purpose bit flag
    centralHeader.writeUInt16LE(COMPRESSION_METHOD_DEFLATE, 10);
    centralHeader.writeUInt16LE(dosTime, 12);
    centralHeader.writeUInt16LE(dosDate, 14);
    centralHeader.writeUInt32LE(uncompressedCrc32, 16);
    centralHeader.writeUInt32LE(compressed.length, 20);
    centralHeader.writeUInt32LE(entry.data.length, 24);
    centralHeader.writeUInt16LE(nameBuffer.length, 28);
    centralHeader.writeUInt16LE(0, 30); // extra field length
    centralHeader.writeUInt16LE(0, 32); // file comment length
    centralHeader.writeUInt16LE(0, 34); // disk number start
    centralHeader.writeUInt16LE(0, 36); // internal file attributes
    centralHeader.writeUInt32LE(0, 38); // external file attributes
    centralHeader.writeUInt32LE(runningOffset, 42); // relative offset of local header

    centralParts.push(centralHeader, nameBuffer);

    runningOffset += localHeader.length + nameBuffer.length + compressed.length;
  }

  const centralDirectory = Buffer.concat(centralParts);
  const centralDirectoryOffset = runningOffset;

  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(END_OF_CENTRAL_DIRECTORY_SIGNATURE, 0);
  eocd.writeUInt16LE(0, 4); // number of this disk
  eocd.writeUInt16LE(0, 6); // disk where central directory starts
  eocd.writeUInt16LE(entries.length, 8); // central directory records on this disk
  eocd.writeUInt16LE(entries.length, 10); // total central directory records
  eocd.writeUInt32LE(centralDirectory.length, 12); // size of central directory
  eocd.writeUInt32LE(centralDirectoryOffset, 16); // offset of start of central directory
  eocd.writeUInt16LE(0, 20); // .ZIP file comment length

  return Buffer.concat([...localParts, centralDirectory, eocd]);
}
